services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    ports:
      - "443:443"
    env_file: ".env"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./mariadb
    env_file: ".env"
    restart: on-failure
