x-common-conf: &common
  env_file: ".env"
  restart: on-failure

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    ports:
      - "443:443"
    <<: *common

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./mariadb
    <<: *common

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./wordpress
    depends_on:
      - mariadb
      - nginx
    <<: *common

