x-common-conf: &common
  networks:
    - inception
  env_file: ".env"
  restart: on-failure

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    <<: *common

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    <<: *common

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./wordpress
    depends_on:
      - mariadb
      - nginx
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - 9000
    <<: *common

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wordpress

networks:
  inception:
    name: inception
